package kirjasotoGUI_final;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


public class KäyttöGUI extends javax.swing.JFrame {

   
	private static final long serialVersionUID = 8339804282211215864L;

    public KäyttöGUI() {
        initComponents();
        Tiedot_Jtableen();
    }

    String ImgPath = null;
    int pos = 0;
    
      // Yhdistäminen tietokantaan
    
    public Connection getConnection()
    {
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql:sql7.freemysqlhosting.net","sql7268384","RizJUWdqkj");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(KäyttöGUI.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    // Syötteiden tarkistus
    public boolean tarkistusInput()
    {
        if(
              txt_tekijänimi.getText() == null 
           || txt_julkaisuvuosi.getText() == null 
           || txt_teoksennimi.getText() == null 

          ){
            return false;
        }
        else{
            try{
                Float.parseFloat(txt_teoksennimi.getText());
                return true;
            }catch(Exception ex)
            {
                return false;
            }
        }
    }

            
   
  // Kuvan sovittaminen JLabeliin
    public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;
        
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    // Tiedot JTableen
    
    public ArrayList<Tiedot> getTiedotLista()
    {
            ArrayList<Tiedot> tiedotLista  = new ArrayList<Tiedot>();
            Connection con = getConnection();
            String query = "SELECT * FROM products";
            
            Statement st;
            ResultSet rs;
            
        try {
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Tiedot tiedot;
            
            while(rs.next())
            {
                tiedot = new Tiedot(rs.getInt("julkaisuvuosi"),rs.getString("tekijänimi"),rs.getString("teoksennimi"),rs.getBytes("image"));
                tiedotLista.add(tiedot);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(KäyttöGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return tiedotLista; 
                
    }
    
    
    //      Täyttö
    
    public void Tiedot_Jtableen()
    {
        ArrayList<Tiedot> list = getTiedotLista();
        DefaultTableModel model = (DefaultTableModel)JTable_Tiedot.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getJulkaisuvuosi();
            row[1] = list.get(i).getTekijänimi();
            row[2] = list.get(i).getTeoksennimi();
          
            
            model.addRow(row);
        }
    
    }
    
    // Data syötteisiin
    public void NäytäTieto(int index)
    {
    	txt_julkaisuvuosi.setText(Integer.toString(getTiedotLista().get(index).getJulkaisuvuosi()));
            txt_tekijänimi.setText(getTiedotLista().get(index).getTekijänimi());
            txt_teoksennimi.setText(getTiedotLista().get(index).getTeoksennimi());
            
        lbl_image.setIcon(ResizeImage(null, getTiedotLista().get(index).getImage()));
        
        lbl_image.setIcon(ResizeImage(null, getTiedotLista().get(index).getImage()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_tekijänimi = new javax.swing.JTextField();
        txt_julkaisuvuosi = new javax.swing.JTextField();
        txt_teoksennimi = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Tiedot = new javax.swing.JTable();
        Btn_valinta_Kuva = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Btn_Lisää = new javax.swing.JButton();
        Btn_Ensimmäinen = new javax.swing.JButton();
        Btn_Edellinen = new javax.swing.JButton();
        Btn_Last = new javax.swing.JButton();
        Btn_Seuraava = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Julkaisuvuosi:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tekijännimi:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Teoksennimi:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Image:");

        txt_tekijänimi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_tekijänimi.setPreferredSize(new java.awt.Dimension(59, 50));

        txt_julkaisuvuosi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_julkaisuvuosi.setEnabled(false);
        txt_julkaisuvuosi.setPreferredSize(new java.awt.Dimension(59, 50));

        txt_teoksennimi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teoksennimi.setPreferredSize(new java.awt.Dimension(59, 50));


        lbl_image.setBackground(new java.awt.Color(204, 255, 255));
        lbl_image.setOpaque(true);

        JTable_Tiedot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Julkaisuvuosi", "Tekijännimi", "Teoksennimi"
            }
        ));
        JTable_Tiedot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	JTable_TiedotMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_Tiedot);

        Btn_valinta_Kuva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_valinta_Kuva.setText("Valitse kuva");
        Btn_valinta_Kuva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Btn_valinta_KuvaActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sälät/icons/Renew.png")));
        jButton2.setText("Päivitä");
        jButton2.setIconTextGap(15);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });


        Btn_Lisää.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Lisää.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sälät/icons/add.png"))); // NOI18N
        Btn_Lisää.setText("Lisää");
        Btn_Lisää.setIconTextGap(15);
        Btn_Lisää.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Btn_LisääActionPerformed(evt);
            }
        });

        Btn_Ensimmäinen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Ensimmäinen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sälät/icons/first.png"))); // NOI18N
        Btn_Ensimmäinen.setText("First");
        Btn_Ensimmäinen.setIconTextGap(15);
        Btn_Ensimmäinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Btn_EnsimmäinenActionPerformed(evt);
            }
        });

        Btn_Edellinen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Edellinen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sälät/icons/previous.png"))); // NOI18N
        Btn_Edellinen.setText("Edellinen");
        Btn_Edellinen.setIconTextGap(15);
        Btn_Edellinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Btn_EdellinenActionPerformed(evt);
            }
        });

        Btn_Last.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sälät/icons/last.png"))); // NOI18N
        Btn_Last.setText("Last");
        Btn_Last.setIconTextGap(15);
        Btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LastActionPerformed(evt);
            }
        });

        Btn_Seuraava.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Seuraava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sälät/icons/next.png"))); // NOI18N
        Btn_Seuraava.setText("Seuraava");
        Btn_Seuraava.setIconTextGap(15);
        Btn_Seuraava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Btn_SeuraavaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_valinta_Kuva, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(txt_julkaisuvuosi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tekijänimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_teoksennimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Lisää)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Ensimmäinen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Seuraava)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Edellinen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Last)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_julkaisuvuosi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tekijänimi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_teoksennimi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Btn_valinta_Kuva, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Lisää, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Ensimmäinen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Seuraava, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Edellinen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        ))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_valinta_KuvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_valinta_KuvaActionPerformed
        
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_image.setIcon(ResizeImage(path, null));
            ImgPath = path;
        }
        else{
            System.out.println("No File Selected");
        }
        
    }//GEN-LAST:event_Btn_valinta_KuvaActionPerformed

    // Kuva / SQL
  
    private void Btn_LisääActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LisääActionPerformed
        
        if(tarkistusInput() && ImgPath != null)
        {
            try {
                 Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO products(teoksennimi,tekijänimi,julkaisuvuosi,image)"
                        + "values(?,?,?,?) ");
                ps.setString(1, txt_tekijänimi.getText());
                ps.setString(2, txt_teoksennimi.getText());
                ps.setString(3, txt_julkaisuvuosi.getText());
               
                
                InputStream img = new FileInputStream(new File(ImgPath));
                ps.setBlob(4, img);
                Tiedot_Jtableen();
                
                JOptionPane.showMessageDialog(null, "Tiedot Lisätty");
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Virhe");
        }
        
        System.out.println("Tekijännimi => "+txt_tekijänimi.getText());
        System.out.println("Teoksennimi => "+txt_teoksennimi.getText());
        System.out.println("Julkaisuvuosi => "+txt_julkaisuvuosi.getText());
        System.out.println("Image => "+ImgPath);
    }//GEN-LAST:event_Btn_LisääActionPerformed

    
    // Syötteen tarkistus
 
    // Datan päivitys
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        if(tarkistusInput() && txt_julkaisuvuosi.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = getConnection();
            
            // Tietojen lisääminen
            
                try{
                InputStream img = new FileInputStream(new File(ImgPath));
                
                 UpdateQuery = "Päivitä tiedot aseta tekijännimi = ?, teoksennimi = ?, julkaisuvuosi = ?, kuva = ?";
                          
                 
                  ps = con.prepareStatement(UpdateQuery);
                    
                    ps.setString(1, txt_tekijänimi.getText());
                    ps.setString(2, txt_teoksennimi.getText());
                    ps.setInt(3, Integer.parseInt(txt_julkaisuvuosi.getText()));
                    ps.setBlob(4, img);
                    
                    
                    
                    ps.executeUpdate();
                    Tiedot_Jtableen();
                    JOptionPane.showMessageDialog(null, "Product Updated");
                
                }catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
   
        }
        
    //GEN-LAST:event_jButton2ActionPerformed

    // Tietokannasta tiedon poistaminen
    ///
    
    // JTable Mouse Clicked
    // Display The Selected Row Data Into JTextFields
    // And The Image Into JLabel
    private void JTable_TiedotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_TiedotMouseClicked
        
        int index = JTable_Tiedot.getSelectedRow();
        NäytäTieto(index);
        
    }//GEN-LAST:event_JTable_TiedotMouseClicked

    // Button First Show The First Record
    private void Btn_EnsimmäinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnsimmäinenActionPerformed
       pos = 0;
       NäytäTieto(pos);
    }//GEN-LAST:event_Btn_EnsimmäinenActionPerformed
    // Button Last Show The Last Record 
    private void Btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LastActionPerformed
       pos = getTiedotLista().size()-1;
       NäytäTieto(pos);
    }//GEN-LAST:event_Btn_LastActionPerformed
    
  // Seuraavan näyttäminen
    
    private void Btn_SeuraavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SeuraavaActionPerformed
       
        pos++;
        
        if(pos >= getTiedotLista().size())
        {
            pos = getTiedotLista().size()-1;
        }
        
        NäytäTieto(pos);
        
    }//GEN-LAST:event_Btn_SeuraavaActionPerformed
  // Button Previous Show The Previous Record
    private void Btn_EdellinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EdellinenActionPerformed
  
        pos--;
        
        if(pos < 0)
        {
            pos = 0;
        }
        
        NäytäTieto(pos);
        
    }//GEN-LAST:event_Btn_EdellinenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KäyttöGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KäyttöGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KäyttöGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KäyttöGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KäyttöGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_valinta_Kuva;
    private javax.swing.JButton Btn_Ensimmäinen;
    private javax.swing.JButton Btn_Lisää;
    private javax.swing.JButton Btn_Last;
    private javax.swing.JButton Btn_Seuraava;
    private javax.swing.JButton Btn_Edellinen;
    private javax.swing.JTable JTable_Tiedot;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField txt_julkaisuvuosi;
    private javax.swing.JTextField txt_tekijänimi;
    private javax.swing.JTextField txt_teoksennimi;
    // End of variables declaration//GEN-END:variables
}
